image: python:3.6-slim

variables:
  BOT_IMAGE: $DOCKERHUB_USER/bot
  COACH_IMAGE: $DOCKERHUB_USER/coach
  COACH_TEMP_IMAGE: $CI_REGISTRY_IMAGE/ci/coach:$CI_COMMIT_SHORT_SHA
  BOT_TEMP_IMAGE: $CI_REGISTRY_IMAGE/ci/bot:$CI_COMMIT_SHORT_SHA

stages:
  - test style
  - test stories
  - build requirements
  - build coach
  - build


#############################################################
#################### TEST STYLE #############################
#############################################################
test style:
  stage: test style
  script:
    - pip -V
    - python -V
    - pip install -r requirements.txt
    - flake8 --exclude venv


#############################################################
############### TEST STORIES ################################
#############################################################
test stories:
  stage: test stories
  image: docker
  tags:
    - docker
  services:
    - docker:dind
  script:
    - docker build -f docker/coach.Dockerfile -t $COACH_TEMP_IMAGE .
    - docker build -f docker/bot.Dockerfile -t $BOT_TEMP_IMAGE .
    - docker run --rm $BOT_TEMP_IMAGE make test-stories
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY # logs in to gitlab registry
    - docker push $COACH_TEMP_IMAGE
    - docker push $BOT_TEMP_IMAGE


#############################################################
############### BUILD REQUIREMENTS ##########################
#############################################################
build requirements:
  stage: build requirements
  image: docker
  tags:
    - docker
  services:
    - docker:dind
  script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
    - cd ./docker/bot
    - ./build-base.sh publish
  only:
    refs:
      - master
      - gitlabci
    changes:
      - ./docker/bot/requirements.txt
  environment: homolog


#############################################################
############### BUILD COACH #################################
#############################################################
build coach:
  stage: build coach
  image: docker
  tags:
    - docker
  services:
    - docker:dind
  script:
    # - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD # Logs in to dockerhub
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY 
    - docker pull $COACH_TEMP_IMAGE
    - docker tag $COACH_TEMP_IMAGE $COACH_IMAGE:latest
    # - docker push $COACH_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE/$COACH_IMAGE:latest
  only:
    - master
    - gitlabci
  environment: homolog


#############################################################
############### BUILD BOT ###################################
#############################################################
build bot:
  stage: build
  image: docker
  tags:
    - docker
  services:
    - docker:dind
  script:
    # - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD # Logs in to dockerhub
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker pull $BOT_TEMP_IMAGE
    - docker tag $BOT_TEMP_IMAGE $BOT_IMAGE:latest
    # - docker push $BOT_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE/$BOT_IMAGE:latest
  only:
    - master
    - gitlabci
  environment: homolog
