version: '2'

services:
  # ============================= Rocketchat ==================================
  rocketchat:
    container_name: rocketchat
    image: rocket.chat:0.69.2
    restart: unless-stopped
    env_file:
      - docker/rocketchat.env
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128

  # =============================== Coach =================================  
  coach:
    container_name: coach
    image: botcoach:latest
    volumes:
      - notebook_models:/notebook_models
    command: sh -c "cp -r /src_models/* /notebook_models"

  # ================================= Bot =====================================
  bot:
    image: lappis/bot:boilerplate
    container_name: bot_rocketchat
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    restart: unless-stopped
    command: make run-console
    env_file:
      - docker/bot-rocketchat.env
    ports:
      - 5002:5002
    volumes:
      - ./bot:/bot
      - ./scripts:/scripts

  # ============================ Telegram Bot =================================
  bot_telegram:
      container_name: bot_telegram
      build:
        context: .
        dockerfile: ./docker/bot.Dockerfile
      env_file:
        - docker/bot-telegram.env
      ports:
        - 5001:5001
      depends_on:
        - actions
      volumes:
        - ./bot:/bot
        - ./scripts:/scripts
      command: sh -c "make run-telegram"

  # ================================= Actions =================================
  actions:
    container_name: actions
    build:
      context: .
      dockerfile: ./docker/actions.Dockerfile
    ports:
      - 5055:5055
    environment:
      - BOTS=localhost:5006;localhost:5007
    volumes:
      - ./bot/actions:/bot/actions
      - ./bot/Makefile:/bot/Makefile
    command: sh -c "make run-actions"

  tais:
    image: lappis/bot:latest
    restart: unless-stopped
    command: make run-api
    env_file:
      - docker/bot.env
    ports:
      - 5006:5005
      - 5003:5002
  # =============================== Notebooks =================================
  notebooks:
    container_name: notebooks
    build:
      context: .
      dockerfile: ./docker/notebooks.Dockerfile
    env_file:
      - docker/notebooks.env
    volumes:
      - ./coach:/work/coach
      - ./notebooks:/work/notebooks
      - notebook_models:/models:ro
    ports:
      - 8888:8888
    depends_on:
      - coach
  
volumes:
  notebook_models:
