policies:
  - name: KerasPolicy
    priority: 5
    epochs: 20
    batch_size: 10
    featurizer:
      - name: FullDialogueTrackerFeaturizer
        state_featurizer:
          - name: LabelTokenizerSingleStateFeaturizer
  - name: FallbackPolicy
    nlu_threshold: 0.6
    core_threshold: 0.6
    priority: 1
  - name: MemoizationPolicy
    priority: 3
    max_history: 2
  - name: "policies.bottis_policy.BottisPolicy"
    priority: 2
    custom_response_action_name: "action_custom_response"
